<div class="box vaf vaf-search">
	<div class="vaf-search-top"></div>
	<div class="vaf-search-middle">
    <div class="head"><h4><?=$this->getHeaderText()?></h4></div>
    <div class="content">                            
    	<?php
		Elite_Vaf_Helper_Data::getInstance()->storeFitInSession();
		?>
    	<?=$this->renderBefore()?>
    	
        <!-- start "My Garage" -->
        <?php
        if( $this->shouldShowMyGarageActive()  )
        {
            $vehicle = $this->getFlexibleDefinition()
            ?>
            <div class="vafMyGarageActive">
                <strong>My Vehicle:</strong> <?=$this->htmlEscape( $vehicle->__toString() )?>
                <br />
                <a href="#" class="vafMyGarageChange">Change</a>
                <?php
                if( $this->showClearButton() )
                {
                    ?>
                    <a href="#" id="vafClear"><?=$this->getClearText()?></a>
                    <?php
                }
                ?>
            </div>
            <?php
        }
        ?>
        <!-- end "My Garage" -->
        
        <form action="<?=$this->action()?>" method="<?=$this->getMethod()?>" id="<?=$this->formId()?>" name="<?=$this->formId()?>">
            <input type="hidden" id="vafProduct" value="<?=$this->getProductId()?>" />
            <?=$this->proxyValues();?>
            <!-- start "category chooser" --> 
            <?php
            if( $this->showCategoryChooser() )
            {
                ?>
                <label>Category:</label>
                <select name="category" id="categorySelect" style="width:160px"> 
                    <?=$this->renderCategoryOptions()?>
                </select>
                <?php
                if(Elite_Vaf_Helper_Data::getInstance()->displayBrTag())
                {
					echo '<br />';
                }
            }
            else
            { 
                echo '<input type="hidden" name="category" id="categorySelect" value="?" />'; 
            }
            ?>
            <!-- end "category chooser" --> 
            
            <?php
            $levels = $this->getLevels();
            
            $helper = new Elite_Vaf_View_Helper_SearchLevel();
            
            $displayLevels = $this->getLevels();
            $c = count( $displayLevels );
            
            for( $i = 0; $i < $c; $i++ )
            {
		
                $level = $displayLevels[ $i ];
                $prevLevel = ( $i > 0 ) ? $displayLevels[ $i - 1 ] : false;
                echo $helper->display( $this, $level, $prevLevel );
		
            }
            
            if( $this->showSearchButton() )
            {
                ?>
		
                <div class="vafButtons">
                    <?php
                    // clear button
                    if( $this->showClearButton()  )
                    {
                        if( 'link' == $this->clearButton() )
                        {
                            ?><a href="#" id="vafClear"><?=$this->getClearText()?></a><?php
                        }
                        else
                        {
                            ?><input type="button" id="vafClear" value="<?=$this->getClearText()?>" /><?php
                        }
                    }
                    
                    echo ' ';
                    
                    // search button
                    if( 'link' == $this->searchButton() )
                    {
                        ?><a href="#" class="vafSubmit"><?=$this->getSubmitText()?></a><?php
                    }
                    else
                    {
                        ?><input type="button" value="<?=$this->getSubmitText()?>" class="vafSubmit" /><?php
                    }
                    ?>
                    
                </div>
                <?php
            }
            ?>
        </form>
        <form id="fake">
        		<div class="fakeButton">
        			<p class="valid_label" id="valid_make" style="visibility: hidden; clear: both; display: none; text-align: center; margin-right: 20px;">Please select vehicle make </p>
        			<p class="valid_label" id="valid_model" style="visibility: hidden; clear: both; display: none; text-align: center; margin-right: 20px;">Please select vehicle model </p>
        			<p class="valid_label" id="valid_message" style="visibility: hidden; clear: both; display: block; text-align: center; margin-right: 20px;"> </p>
            		<input type="button" value="SEARCH" class="vafSubmit" id="foo" name="foo" style="display:none;" />
            </div>
        </form>
    </div>
    </div>
    <div class="vaf-search-bottom"></div>
</div>
<script type="text/javascript">

	//jQuery(document).ready(function() {

	// });	
		
		//jQuery("#foo").click(function() {
		
		/*
		jQuery(".vafSubmit").click(function() {
		
		var year = false;
		var make = false;
		var model = false;
		
		var problems = new Array();
		
	
		var message = "Please select vehicle ";
		var notices = "";

	
		//jQuery("#foo").css({"display":"none"});
		
		i = 0;
		
			if(jQuery(".yearSelect option[value='0']").attr('selected')){
				problems[i] = "Year";
				i++;
			}
			else { year = true; }
		
			if(jQuery(".makeSelect option[value='0']").attr('selected')){				
				problems[i] = "Make";
				i++;
			}
			else { make = true; }
			
			if(jQuery(".modelSelect option[value='0']").attr('selected')){
				problems[i] = "Model";
				i++;
			}
			else { model = true; }
			
			for(var x = 0; x < problems.length; x++)
			{
				notices += " "+problems[x];
				if(x != problems.length-1) {
					notices += ", ";
				}
			}
			
			
			// if all the dropdowns are selected, submit the form
			// needed if the user navigates back to home after having completed a search			
			if( (year==true)&&(make==true)&&(model==true)
				) {
				
				// jQuery("#valid_message").css({"visibility":"hidden"});
				//alert("now?");
				jQuery("#<?=$this->formId()?>").submit();
			}
			else
			{
				jQuery("#valid_message").html(message+notices+".");
				jQuery("#valid_message").css({"visibility":"visible"});
			}
			
		
			
		});
	
		*/

</script>